export const DANG_NHAP_ACTION="DANG_NHAP_ACTION";
export const DANG_KY_ACTION="DANG_KY_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG="SET_THONG_TIN_NGUOI_DUNG";

// GET USERS
export const GET_USERS_PAG="GET_USERS_PAG";
export const GET_USERS="GET_USERS";

//LOAI NGƯỜI DÙNG

export const GET_USER_TYPES="GET_USER_TYPES";
export const SEARCH_USERS="SEARCH_USERS";


//LẤY THÔNG TIN USERS
export const GET_INFO_USER="GET_INFO_USER"