export const DANG_NHAP_ACTION="DANG_NHAP_ACTION";
export const DANG_KY_ACTION="DANG_KY_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG="SET_THONG_TIN_NGUOI_DUNG";

// GET USERS
export const GET_USERS="GET_USERS";